server:
    port: 8081
    shiro:
        encrypt:
            hashAlgorithmName: md5
            hashIterations: 2
            storedCredentialsHexEncoded: true
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1/boot-showcase?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Admin123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker:
        template-loader-path: classpath:/freemarker/
        suffix: .ftl
        cache: false
        order: 1
        contentType: text/html;charset=utf-8
        requestContextAttribute: rc
        exposeSpringMacroHelpers: true